### ISSUE TITLE
Provisioning Engine: ListId token does not contain the id of a created list when the rootsite contains a list with the same title

### ISSUE THREAD

**Issue by artokai** [OfficeDev/PnP-Sites-Core#809]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

Tested only in SharePoint Online, but this should not be environment dependent bug.

#### Expected or Desired Behavior

When provisioning a list in a subsite the listId-token should  always contain the id of the newly created list and not a listId from the rootweb of the site collection.

#### Observed Behavior

ListId-token always contains the id of the list in the sitecollection's rootweb even if a list with the same title is provisioned in the subsite. This prevents you from using the newly created list's id in webpart definitions.

#### Steps to Reproduce

1. Create a site collection
2. Create a task list with the title "Tasks" in the site collection's rootweb.
3. Create a subsite to the site collection
4. Apply a provisioning template in the subweb. This provisioning template should include a task list with the title 'Tasks' and a webpart which uses the token`{listid:Tasks`}

After the template is provisioned, the provisioned webpart is configure using the rootsite's listid and not the listid of the task-list in the subweb.

This probably happens because the newly created token is always added to the end of of the token in [TokenParser.cs, AddToken, Line 35](https://github.com/OfficeDev/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs#L35).

#### Workaround

Provision the list using some other title in the subweb (for example "SubwebTasks"} and then change the title programmatically after the template has been applied. Even though the listid of the newly created list is added to the tokens-list, it will be added after the token from the rootweb and therefore the rootweb's token takes precedence.

#### Questions and thoughts

Is this by design or is this a bug? If this is by design, then how can you get the list id of the newly created list in the template?

Perhaps the list id's of the root web should be accessible also through some other token than `{listid:listtitle}`.  We could for example provide a token called `{root_listid:listtitle}` and override the original `{listid:listtitle}` token if a matching list is found or created in the subweb. This way the template would have access to both rootweb's listids and subweb's ids even when those lists have identical titles.

**Comment by jansenbe** [comment]
**Internal testing feedback**
Followed the steps as mentioned by the user.
Provisioned tasks list and web part in sub site
Web part displayed content of sub site task lists data.


@artokai : can you retest this scenario with the latest version, based on our testing the issue is fixed

**Comment by artokai** [comment]
Hello and sorry about the delay. Unfortunately I can still reproduce the issue with PnP version "2.12.1702.0".

I have a template which contains a simple custom list called "testlist" and a page with a Content Editor Webpart. The contents of the content editor webpart is basically just "CustomListID = {listid:testlist}". 

My test code works like this:

1. Apply the template to the rootWeb
2. Create a new subsite
3. Apply the same template to the subweb

Because the subweb also contains a list the title "testlist", I would expect the page in the subweb would show a differrent ListId. Unfortunately this is not the case. Both webparts are displaying the same listId.

- Page in the rootweb displays: `CustomListID = 205c0074-5ca8-4f7d-88d2-d990af1ece08 `
- Page in the subweb displays: `CustomListID = 205c0074-5ca8-4f7d-88d2-d990af1ece08`

The correct listid of the list in the subweb is actually `8773c764-0761-4fd0-b2d7-7b5218bd85d1`

I also tried applying the templates separately to make sure that nothing is cached in PnP Core or in the ClientContext. This had no difference to the end result. The page in the subweb is still showing the listid of the list in the parent web.

I used the following code to test this. My test template can be found [in this gist](https://gist.github.com/artokai/39a730ca7d578c19ef99235c08ff3a48). (I know that it's using a little bit older schema, but that should not affect how the token replacement works.)

```
// Load template which contains: 
// - A custom list  and 
// - A Page with a single ContentEditorWebPart with the content "CustomListId = {listid:testlist} "
Console.WriteLine("Loading template");
var provider = new XMLFileSystemTemplateProvider(@"C:\temp\templates\", "");
var template = provider.GetTemplate(@"template.xml");

// Apply template to root site
Console.WriteLine("Applying template to rootweb");
var rootWeb = ctx.Web;
rootWeb.ApplyProvisioningTemplate(template);
ctx.ExecuteQueryRetry();

// Create subweb
var title = "w" + DateTime.Now.Ticks;
Console.WriteLine("Creating subweb: " + title);
var subweb = rootWeb.CreateWeb(title, title, "", "STS#0", 1033);
ctx.Load(subweb, w => w.Url);
ctx.ExecuteQueryRetry();

// Apply template to subweb
Console.WriteLine("Applying template to subweb");
subweb.ApplyProvisioningTemplate(template);
ctx.ExecuteQueryRetry();
```

**Comment by jansenbe** [comment]
Thanks @artokai , so we'll need to further spent time on this one :-)

**Comment by RobinBreman** [comment]
Yesterday i've submitted a new issue (#1239 ), a possible duplicate to this one, but it explains why the listid token contains an invalid listid.
[TokenParser.cs#L86 - L102](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs#L86 )   seems to cause this issue.

**Comment by DeLuca-Marco** [comment]
Hello,
I was working with 2.22.1801 and listid-Token was resolved correctly in lookup field schemaXML of Root- and Subsite. Now with 3.0.1808 I encounter the same issue as described in this Bug report.
